// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrameTestEnum.proto

#ifndef PROTOBUF_INCLUDED_FrameTestEnum_2eproto
#define PROTOBUF_INCLUDED_FrameTestEnum_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include "nanopb.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_FrameTestEnum_2eproto 

namespace protobuf_FrameTestEnum_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_FrameTestEnum_2eproto
namespace NFrameEnum {
}  // namespace NFrameEnum
namespace NFrameEnum {

enum FrameGlobalTestEnum {
  SERVER_TEST_ENUM_NONE2 = 0,
  FRAME_ENUM_STRING_NUM = 68,
  FRAME_ENUM_DEFAULT_REPEATED = 2,
  FrameGlobalTestEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  FrameGlobalTestEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool FrameGlobalTestEnum_IsValid(int value);
const FrameGlobalTestEnum FrameGlobalTestEnum_MIN = SERVER_TEST_ENUM_NONE2;
const FrameGlobalTestEnum FrameGlobalTestEnum_MAX = FRAME_ENUM_STRING_NUM;
const int FrameGlobalTestEnum_ARRAYSIZE = FrameGlobalTestEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrameGlobalTestEnum_descriptor();
inline const ::std::string& FrameGlobalTestEnum_Name(FrameGlobalTestEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrameGlobalTestEnum_descriptor(), value);
}
inline bool FrameGlobalTestEnum_Parse(
    const ::std::string& name, FrameGlobalTestEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrameGlobalTestEnum>(
    FrameGlobalTestEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace NFrameEnum

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::NFrameEnum::FrameGlobalTestEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFrameEnum::FrameGlobalTestEnum>() {
  return ::NFrameEnum::FrameGlobalTestEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_FrameTestEnum_2eproto
