/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 */

#ifndef PB_NFRAMEENUM_FRAMETESTENUM_NANOPB_H_INCLUDED
#define PB_NFRAMEENUM_FRAMETESTENUM_NANOPB_H_INCLUDED
#include <string>
#include <vector>
#include <unordered_map>
#include <map>
#include <NFComm/NFCore/NFHash.hpp>
#include <pb.h>

#include "FrameTestEnum.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _FrameGlobalTestEnum {
    SERVER_TEST_ENUM_NONE2 = 0,
    FRAME_ENUM_STRING_NUM = 68,
    FRAME_ENUM_DEFAULT_REPEATED = 2
} FrameGlobalTestEnum;
#define _FrameGlobalTestEnum_MIN SERVER_TEST_ENUM_NONE2
#define _FrameGlobalTestEnum_MAX FRAME_ENUM_DEFAULT_REPEATED
#define _FrameGlobalTestEnum_ARRAYSIZE ((FrameGlobalTestEnum)(FRAME_ENUM_DEFAULT_REPEATED+1))
#define _FrameGlobalTestEnum_ALLSIZE (3)

/* @@protoc_insertion_point(eof) */

#endif
