// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerError.proto

#ifndef PROTOBUF_INCLUDED_ServerError_2eproto
#define PROTOBUF_INCLUDED_ServerError_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include "nanopb.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ServerError_2eproto 

namespace protobuf_ServerError_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ServerError_2eproto
namespace NFServer {
}  // namespace NFServer
namespace NFServer {

enum Proto_SVR_ErrorCode {
  ERR_SERVER_CODE_ZERO = 0,
  ERR_CODE_SERVER_SYSTEM_ERROR = -1,
  Proto_SVR_ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Proto_SVR_ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Proto_SVR_ErrorCode_IsValid(int value);
const Proto_SVR_ErrorCode Proto_SVR_ErrorCode_MIN = ERR_CODE_SERVER_SYSTEM_ERROR;
const Proto_SVR_ErrorCode Proto_SVR_ErrorCode_MAX = ERR_SERVER_CODE_ZERO;
const int Proto_SVR_ErrorCode_ARRAYSIZE = Proto_SVR_ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto_SVR_ErrorCode_descriptor();
inline const ::std::string& Proto_SVR_ErrorCode_Name(Proto_SVR_ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto_SVR_ErrorCode_descriptor(), value);
}
inline bool Proto_SVR_ErrorCode_Parse(
    const ::std::string& name, Proto_SVR_ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto_SVR_ErrorCode>(
    Proto_SVR_ErrorCode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace NFServer

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::NFServer::Proto_SVR_ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NFServer::Proto_SVR_ErrorCode>() {
  return ::NFServer::Proto_SVR_ErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ServerError_2eproto
