/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 */

#ifndef PB_NFSERVER_SERVERERROR_NANOPB_H_INCLUDED
#define PB_NFSERVER_SERVERERROR_NANOPB_H_INCLUDED
#include <string>
#include <vector>
#include <unordered_map>
#include <map>
#include <NFComm/NFCore/NFHash.hpp>
#include <pb.h>

#include "ServerError.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Proto_SVR_ErrorCode {
    ERR_SERVER_CODE_ZERO = 0,
    ERR_CODE_SERVER_SYSTEM_ERROR = -1
} Proto_SVR_ErrorCode;
#define _Proto_SVR_ErrorCode_MIN ERR_SERVER_CODE_ZERO
#define _Proto_SVR_ErrorCode_MAX ERR_CODE_SERVER_SYSTEM_ERROR
#define _Proto_SVR_ErrorCode_ARRAYSIZE ((Proto_SVR_ErrorCode)(ERR_CODE_SERVER_SYSTEM_ERROR+1))
#define _Proto_SVR_ErrorCode_ALLSIZE (2)

/* @@protoc_insertion_point(eof) */

#endif
